name: Lint Markdown

on:
  push:
    paths:
      - "**/*.md"
      - ".github/workflows/lint.yml"
  pull_request:
    paths:
      - "**/*.md"

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint markdown
        uses: articulate/actions-markdownlint@v1
        with:
          files: |
            **/*.md
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Run Ruff
        run: |
          ruff check .
